version: '3'

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'jupyterhub'
    ports:
      - '80:8000'
    volumes:
      - ./jupyter_data:/home/admin
      - .${NOTEBOOKS_FROM}:/home/admin${HUB_PATH}

volumes:
  jupyter_data: